#!/usr/bin/env python3
"""Generate negatives and rewrite-eval rows for the DLP sentinel classifier.

Today's corpus is 100% confidential. This adds three kinds of rows so the
sentinel learns "internal versus public" and "faithful rewrite versus new
content" rather than "pharma versus not pharma": synthetic public text on
the same topic, synthetic internal-but-benign notices, and faithful
rewrites of confidential eval documents. All three are generated by a local
llama-server chat model and filtered with pure acceptance functions before
being written out.
"""

from __future__ import annotations

import argparse
import difflib
import json
import random
import sys
import urllib.error
import urllib.request
import zlib
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from pathlib import Path
from threading import Lock
from typing import Callable

sys.path.insert(0, str(Path(__file__).resolve().parent))
from public_negatives import records as public_negative_records  # noqa: E402

PUBLIC_KINDS = [
    "FDA prescribing information paragraph",
    "SEC 10-K risk factor paragraph",
    "company press release paragraph",
    "clinical trial registry entry",
    "news article paragraph",
    "journal abstract",
]

INTERNAL_KINDS = [
    "facility notice",
    "cafeteria menu",
    "parking update",
    "IT maintenance notice",
    "holiday schedule",
    "training reminder",
    "benefits enrollment reminder",
    "all-hands meeting logistics email",
    "new-hire welcome note",
    "office supply request policy",
]

REFUSAL_PHRASES = ("i cannot", "i can't", "as an ai", "i'm sorry")

PUBLIC_SYSTEM = "You write public-record text about the pharmaceutical industry."
INTERNAL_SYSTEM = "You write routine internal notices for employees."
REWRITE_SYSTEM = "You rewrite documents faithfully."

REWRITE_EXCERPT_CHARS = 2500


def leaks(candidate: str, source: str, n: int = 12) -> bool:
    """True when any run of n consecutive lowercase words of source appears in candidate."""
    src_words = source.lower().split()
    cand_words = candidate.lower().split()
    if len(src_words) < n or len(cand_words) < n:
        return False
    windows = {tuple(cand_words[i : i + n]) for i in range(len(cand_words) - n + 1)}
    return any(tuple(src_words[i : i + n]) in windows for i in range(len(src_words) - n + 1))


def accept_negative(text: str) -> bool:
    if len(text.split()) < 40:
        return False
    lowered = text.lower()
    return not any(phrase in lowered for phrase in REFUSAL_PHRASES)


def accept_rewrite(text: str, source: str) -> bool:
    source_words = source.split()
    if not source_words or len(text.split()) < 0.4 * len(source_words):
        return False
    return difflib.SequenceMatcher(None, text, source).ratio() < 0.9


def row_seed(source_id: str, method: str) -> int:
    return zlib.crc32(f"{source_id}|{method}".encode("utf-8")) & 0x7FFFFFFF


def chat(
    server: str,
    messages: list[dict],
    max_tokens: int,
    seed: int,
    temperature: float = 0.8,
    timeout: int = 600,
) -> str:
    payload = {
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
        "seed": seed,
    }
    body = json.dumps(payload).encode()
    req = urllib.request.Request(
        f"{server}/v1/chat/completions", data=body, headers={"Content-Type": "application/json"}
    )
    for attempt in range(2):
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                reply = json.load(resp)
            return reply["choices"][0]["message"].get("content") or ""
        except OSError:
            if attempt == 1:
                raise
    raise AssertionError("unreachable")


def public_messages(positive: dict, kind: str) -> list[dict]:
    excerpt = positive["text"][:1500]
    user = (
        f"{excerpt}\n\n"
        f"Write a {kind} on the same topic, 80 to 200 words, that could be published "
        "openly. Do not copy any sentence, person name, address, phone number, email "
        "address, or identifier from the excerpt. Output only the text."
    )
    return [{"role": "system", "content": PUBLIC_SYSTEM}, {"role": "user", "content": user}]


def internal_messages(kind: str) -> list[dict]:
    user = (
        f"Write a {kind} for employees of a pharmaceutical manufacturer, 60 to 180 "
        "words, as an email or memo. It must contain no product sales figures, no "
        "regulatory or legal matters, no customer, prescriber or patient information, "
        "and no financial figures. Output only the text."
    )
    return [{"role": "system", "content": INTERNAL_SYSTEM}, {"role": "user", "content": user}]


def rewrite_messages(positive: dict) -> list[dict]:
    excerpt = positive["text"][:REWRITE_EXCERPT_CHARS]
    user = (
        "Rewrite the following internal document excerpt in different words. Keep "
        "every fact, name, number and identifier. Change sentence structure and "
        "vocabulary. Keep roughly the same length. Output only the rewritten text.\n\n"
        f"{excerpt}"
    )
    return [{"role": "system", "content": REWRITE_SYSTEM}, {"role": "user", "content": user}]


@dataclass
class Task:
    positive: dict
    source_id: str
    method: str  # "synthetic-public" | "synthetic-internal" | "rewrite"
    messages: list[dict]
    seed: int
    split: str


def negative_task(positive: dict, public: bool) -> Task:
    sid, page = positive["source_id"], positive["page"]
    suffix, kinds, method = (
        ("pub", PUBLIC_KINDS, "synthetic-public") if public else ("int", INTERNAL_KINDS, "synthetic-internal")
    )
    source_id = f"{sid}-p{page}-{suffix}"
    seed = row_seed(source_id, method)
    kind = random.Random(seed).choice(kinds)
    messages = public_messages(positive, kind) if public else internal_messages(kind)
    return Task(positive, source_id, method, messages, seed, positive["split"])


def rewrite_task(positive: dict) -> Task:
    sid, page = positive["source_id"], positive["page"]
    source_id = f"{sid}-p{page}-rw"
    seed = row_seed(source_id, "rewrite")
    return Task(positive, source_id, "rewrite", rewrite_messages(positive), seed, positive["split"])


def build_tasks(train: list[dict], eval_rows: list[dict]) -> list[Task]:
    tasks = [negative_task(pos, i % 2 == 0) for i, pos in enumerate(train)]
    for i, pos in enumerate(eval_rows):
        tasks.append(rewrite_task(pos))
        tasks.append(negative_task(pos, i % 2 == 0))
    return tasks


def build_row(task: Task, text: str, generator: str) -> dict:
    pos = task.positive
    if task.method == "rewrite":
        row = {
            "source_id": task.source_id,
            "family": pos["family"],
            "sensitivity": "confidential",
            "category": "internal",
            "split": pos["split"],
            "method": "rewrite",
            "page": pos["page"],
            "n_pages": pos["n_pages"],
            "text": text,
            "visual_tags": pos["visual_tags"],
            "task": pos["task"],
            "project": pos["project"],
            "derived": pos["derived"],
            "source_url": pos["source_url"],
        }
    else:
        sensitivity = "public" if task.method == "synthetic-public" else "internal"
        row = {
            "source_id": task.source_id,
            "family": pos["family"],
            "sensitivity": sensitivity,
            "category": sensitivity,
            "split": pos["split"],
            "method": task.method,
            "page": pos["page"],
            "n_pages": pos["n_pages"],
            "text": text,
            "visual_tags": [],
            "task": pos["task"],
            "project": "unknown",
            "derived": [],
            "source_url": "",
        }
    row["generator"] = generator
    return row


def accepted(task: Task, text: str) -> bool:
    if task.method == "rewrite":
        return accept_rewrite(text, task.positive["text"][:REWRITE_EXCERPT_CHARS])
    return accept_negative(text) and not leaks(text, task.positive["text"])


def load_cache(cache_path: Path) -> dict[str, dict]:
    cache: dict[str, dict] = {}
    if cache_path.exists():
        for line in cache_path.read_text(encoding="utf-8").splitlines():
            if line.strip():
                rec = json.loads(line)
                cache[rec["key"]] = rec
    return cache


def run_task(
    task: Task,
    chat_fn: Callable[..., str],
    server: str,
    max_tokens: int,
    cache: dict[str, dict],
    cache_lock: Lock,
    cache_path: Path,
    generator: str,
) -> tuple[dict | None, str]:
    cached = cache.get(task.source_id)
    if cached is not None:
        text, ok = cached["text"], cached["accepted"]
    else:
        text = chat_fn(server, task.messages, max_tokens, seed=task.seed, temperature=0.8)
        ok = accepted(task, text)
        rec = {"key": task.source_id, "method": task.method, "text": text, "accepted": ok}
        with cache_lock:
            if task.source_id not in cache:
                cache[task.source_id] = rec
                with cache_path.open("a", encoding="utf-8") as f:
                    f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    return (build_row(task, text, generator) if ok else None), task.method


def generate(
    tasks: list[Task],
    out: Path,
    chat_fn: Callable[..., str],
    server: str,
    max_tokens: int,
    workers: int,
    generator: str,
) -> tuple[list[dict], Counter]:
    out.mkdir(parents=True, exist_ok=True)
    cache_path = out / "generations.jsonl"
    cache = load_cache(cache_path)
    cache_lock = Lock()
    with ThreadPoolExecutor(max_workers=workers) as pool:
        results = list(
            pool.map(
                lambda t: run_task(t, chat_fn, server, max_tokens, cache, cache_lock, cache_path, generator),
                tasks,
            )
        )
    rows = [row for row, _ in results if row is not None]
    dropped = Counter(method for row, method in results if row is None)
    return rows, dropped


def counts_by(rows: list[dict]) -> dict:
    tally: dict = {}
    for row in rows:
        split = tally.setdefault(row.get("split", "?"), {})
        sensitivity = split.setdefault(row.get("sensitivity", "?"), {})
        method = row.get("method", "?")
        sensitivity[method] = sensitivity.get(method, 0) + 1
    return tally


def resolve_generator(server: str, generator: str | None) -> str:
    if generator:
        return generator
    req = urllib.request.Request(f"{server}/v1/models")
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.load(resp)
    return data["data"][0]["id"]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--server", default="http://localhost:8090")
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--max-tokens", type=int, default=400)
    ap.add_argument("--generator", default=None)
    args = ap.parse_args()

    train = json.loads((args.data / "train.json").read_text())
    eval_rows = json.loads((args.data / "eval.json").read_text())
    if args.limit is not None:
        train = train[: args.limit]
        eval_rows = eval_rows[: args.limit]

    generator = resolve_generator(args.server, args.generator)
    tasks = build_tasks(train, eval_rows)
    generated, dropped = generate(tasks, args.out, chat, args.server, args.max_tokens, args.workers, generator)

    train_out = train + public_negative_records() + [r for r in generated if r["split"] == "train"]
    eval_out = eval_rows + [r for r in generated if r["split"] == "eval"]
    random.Random(args.seed).shuffle(train_out)
    random.Random(args.seed).shuffle(eval_out)

    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "train.json").write_text(json.dumps(train_out, indent=2, ensure_ascii=False) + "\n")
    (args.out / "eval.json").write_text(json.dumps(eval_out, indent=2, ensure_ascii=False) + "\n")

    manifest = {
        "generator": generator,
        "seed": args.seed,
        "counts": counts_by(train_out + eval_out),
        "dropped": dict(dropped),
    }
    (args.out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
