[package]
name = "arkavo-repo"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Repository mapper for the Arkavo agentic CLI tool - builds semantic map of repositories and tracks changed files"

[dependencies]