[package]
name = "arkavo"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Main binary for the Arkavo agentic CLI tool"
repository.workspace = true
readme = "README.md"
keywords = ["cli", "ai", "agent"]
categories = ["command-line-utilities", "development-tools"]


[features]
default = ["memory", "mdns", "local"]
memory = ["arkavo-cli/memory"]
embeddings = ["memory", "arkavo-cli/embeddings"]
mdns = ["arkavo-cli/mdns"]
local = ["arkavo-cli/local"]
metal = ["arkavo-cli/metal"]
llm-remote = ["arkavo-cli/llm-remote"]

[dependencies]
arkavo-cli = { path = "../arkavo-cli", default-features = false }

[build-dependencies]

[[bin]]
name = "arkavo"
path = "src/main.rs"
[lints]
workspace = true
