[package]
name = "arkavo-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1", features = ["derive"] }

[dependencies.arkavo-protocol]
path = ".."


[[bin]]
name = "fuzz_rate_limit"
path = "fuzz_targets/fuzz_rate_limit.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_json_rpc"
path = "fuzz_targets/fuzz_json_rpc.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_rate_limit_concurrent"
path = "fuzz_targets/fuzz_rate_limit_concurrent.rs"
test = false
doc = false
bench = false
