pub mod anchor_client;
mod ast_crdt;
mod ast_op;
pub mod canonical_store;
pub mod canonical_version;
pub mod capability_token;
pub mod conflict_detector;
mod error;
pub mod materializer;
pub mod merkle_tree;
mod op_bundle;
pub mod pinned_release;
pub mod provenance_query;
pub mod renderer;
pub mod rust_op;
mod target_scope;
pub mod target_scope_overlap;
pub mod vector_clock;
pub mod workspace_harness;

pub use anchor_client::{AnchorClient, AnchorReceipt, AnchorRecord};
pub use ast_crdt::{AcceptedOp, AstCrdt, ConflictPair, PendingOp};
pub use ast_op::AstOp;
pub use canonical_store::CanonicalStore;
pub use canonical_version::{CanonicalVersion, VersionDag};
pub use capability_token::{CapScope, CapabilityToken};
pub use conflict_detector::{ConflictResult, detect_conflict, resolve_disjoint};
pub use error::{Error, Result};
pub use materializer::{BuildReceipt, Materializer};
pub use merkle_tree::{MerkleProof, MerkleTree};
pub use op_bundle::{OpBundle, OpBundleStatus};
pub use pinned_release::{PinnedRelease, ReleaseRegistry};
pub use provenance_query::{ProvenanceQuery, ProvenanceRecord};
pub use renderer::{render_diff_summary, render_file};
pub use rust_op::RustOp;
pub use target_scope::TargetScope;
pub use target_scope_overlap::overlaps;
pub use vector_clock::VectorClock;
pub use workspace_harness::{TempWorkspace, VerificationResult, crate_name_from_path};
