//! Intent analysis trait and types for task decomposition.
//!
//! Provides the `IntentAnalyzer` trait for pluggable intent parsing (rule-based or LLM-backed),
//! along with `IntentAnalysis`, `Entity`, and `SubTaskSpec` types used by the `TaskPlanner`.

use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use crate::task_planner::TaskPlanError;

/// Analyzes user intent to extract structure for task planning.
#[async_trait]
pub trait IntentAnalyzer: Send + Sync {
    async fn analyze(&self, intent: &str) -> Result<IntentAnalysis, TaskPlanError>;
}

/// Result of intent analysis: keywords, entities, and optional LLM-generated subtask specs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IntentAnalysis {
    pub keywords: Vec<String>,
    pub entities: Vec<Entity>,
    /// LLM-generated subtask specifications. Empty for rule-based analysis.
    #[serde(default)]
    pub subtask_specs: Vec<SubTaskSpec>,
}

/// An extracted entity from user intent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Entity {
    pub entity_type: String,
    pub value: String,
}

/// A subtask specification generated by an LLM before UUID assignment.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubTaskSpec {
    pub task_type: String,
    pub description: String,
    #[serde(default)]
    pub required_capabilities: Vec<String>,
    /// Index-based references into the subtask_specs array (0-based).
    /// Tolerates LLM outputs that use string names instead of indices.
    #[serde(default, deserialize_with = "deserialize_depends_on")]
    pub depends_on: Vec<usize>,
}

/// Deserialize `depends_on` tolerantly: accepts `[0, 1]` (indices) or
/// `["analyze", "generate"]` (string names that LLMs sometimes produce).
/// String values are silently dropped since we can't resolve names to indices here.
fn deserialize_depends_on<'de, D>(deserializer: D) -> Result<Vec<usize>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    use serde::de;

    struct DependsOnVisitor;

    impl<'de> de::Visitor<'de> for DependsOnVisitor {
        type Value = Vec<usize>;

        fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
            f.write_str("an array of integers or strings")
        }

        fn visit_seq<A>(self, mut seq: A) -> Result<Self::Value, A::Error>
        where
            A: de::SeqAccess<'de>,
        {
            let mut indices = Vec::new();
            while let Some(val) = seq.next_element::<serde_json::Value>()? {
                if let Some(n) = val.as_u64() {
                    indices.push(n as usize);
                }
                // String values silently ignored — LLMs output names like "analyze"
            }
            Ok(indices)
        }
    }

    deserializer.deserialize_seq(DependsOnVisitor)
}

/// Rule-based intent analyzer using keyword matching.
/// Preserves the legacy `analyze_intent` behavior from the original `TaskPlanner`.
pub struct RuleBasedAnalyzer;

#[async_trait]
impl IntentAnalyzer for RuleBasedAnalyzer {
    async fn analyze(&self, intent: &str) -> Result<IntentAnalysis, TaskPlanError> {
        let intent_lower = intent.to_lowercase();

        let mut keywords = Vec::new();
        let mut entities = Vec::new();

        if intent_lower.contains("nearby") || intent_lower.contains("near me") {
            keywords.push("location".to_string());
            keywords.push("search".to_string());
        }

        if intent_lower.contains("find") || intent_lower.contains("search") {
            keywords.push("search".to_string());
        }

        if intent_lower.contains("with") || intent_lower.contains("that have") {
            keywords.push("filter".to_string());
        }

        if intent_lower.contains("summarize") || intent_lower.contains("summary") {
            keywords.push("summarize".to_string());
        }

        if intent_lower.contains("coffee") {
            entities.push(Entity {
                entity_type: "place_type".to_string(),
                value: "coffee shop".to_string(),
            });
        }

        if intent_lower.contains("outdoor seating") {
            entities.push(Entity {
                entity_type: "amenity".to_string(),
                value: "outdoor seating".to_string(),
            });
        }

        if intent_lower.contains("reviews") || intent_lower.contains("rating") {
            entities.push(Entity {
                entity_type: "filter_criterion".to_string(),
                value: "reviews".to_string(),
            });
        }

        Ok(IntentAnalysis {
            keywords,
            entities,
            subtask_specs: Vec::new(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn rule_based_analyzer_keywords() {
        let analyzer = RuleBasedAnalyzer;
        let analysis = analyzer
            .analyze("Find nearby coffee shops with outdoor seating")
            .await
            .unwrap();

        assert!(analysis.keywords.contains(&"location".to_string()));
        assert!(analysis.keywords.contains(&"search".to_string()));
        assert!(analysis.keywords.contains(&"filter".to_string()));
        assert!(analysis.subtask_specs.is_empty());
    }

    #[tokio::test]
    async fn rule_based_analyzer_entities() {
        let analyzer = RuleBasedAnalyzer;
        let analysis = analyzer
            .analyze("Find coffee shops with outdoor seating and good reviews")
            .await
            .unwrap();

        assert_eq!(analysis.entities.len(), 3);
        assert!(
            analysis
                .entities
                .iter()
                .any(|e| e.entity_type == "place_type")
        );
        assert!(analysis.entities.iter().any(|e| e.entity_type == "amenity"));
        assert!(
            analysis
                .entities
                .iter()
                .any(|e| e.entity_type == "filter_criterion")
        );
    }

    #[test]
    fn subtask_spec_serde_roundtrip() {
        let spec = SubTaskSpec {
            task_type: "web_search".to_string(),
            description: "Search for coffee shops".to_string(),
            required_capabilities: vec!["web_search".to_string()],
            depends_on: vec![0],
        };
        let json = serde_json::to_string(&spec).unwrap();
        let parsed: SubTaskSpec = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.task_type, "web_search");
        assert_eq!(parsed.depends_on, vec![0]);
    }

    #[test]
    fn intent_analysis_serde_with_specs() {
        let json = r#"{
            "keywords": ["search"],
            "entities": [],
            "subtask_specs": [
                {
                    "task_type": "search",
                    "description": "Search for X",
                    "required_capabilities": [],
                    "depends_on": []
                },
                {
                    "task_type": "filter",
                    "description": "Filter results",
                    "required_capabilities": [],
                    "depends_on": [0]
                }
            ]
        }"#;
        let analysis: IntentAnalysis = serde_json::from_str(json).unwrap();
        assert_eq!(analysis.subtask_specs.len(), 2);
        assert_eq!(analysis.subtask_specs[1].depends_on, vec![0]);
    }

    #[test]
    fn intent_analysis_serde_missing_specs_defaults_empty() {
        let json = r#"{"keywords": ["test"], "entities": []}"#;
        let analysis: IntentAnalysis = serde_json::from_str(json).unwrap();
        assert!(analysis.subtask_specs.is_empty());
    }

    #[test]
    fn subtask_spec_defaults_on_missing_fields() {
        let json = r#"{"task_type": "search", "description": "find stuff"}"#;
        let spec: SubTaskSpec = serde_json::from_str(json).unwrap();
        assert!(spec.required_capabilities.is_empty());
        assert!(spec.depends_on.is_empty());
    }

    #[test]
    fn depends_on_tolerates_string_values_from_llm() {
        let json = r#"{
            "keywords": ["colonist beds"],
            "entities": [],
            "subtask_specs": [
                {
                    "task_type": "analyze",
                    "description": "Analyze state",
                    "required_capabilities": [],
                    "depends_on": []
                },
                {
                    "task_type": "execute",
                    "description": "Execute action",
                    "required_capabilities": [],
                    "depends_on": ["analyze"]
                }
            ]
        }"#;
        let analysis: IntentAnalysis = serde_json::from_str(json).unwrap();
        assert_eq!(analysis.subtask_specs.len(), 2);
        // String deps are silently dropped (can't resolve names to indices)
        assert!(analysis.subtask_specs[1].depends_on.is_empty());
    }

    #[tokio::test]
    async fn rule_based_no_keywords_returns_empty() {
        let analyzer = RuleBasedAnalyzer;
        let analysis = analyzer.analyze("hello world").await.unwrap();
        assert!(analysis.keywords.is_empty());
        assert!(analysis.entities.is_empty());
        assert!(analysis.subtask_specs.is_empty());
    }

    #[tokio::test]
    async fn rule_based_summarize_keyword() {
        let analyzer = RuleBasedAnalyzer;
        let analysis = analyzer.analyze("summarize this document").await.unwrap();
        assert!(analysis.keywords.contains(&"summarize".to_string()));
    }

    #[tokio::test]
    async fn rule_based_near_me_triggers_location() {
        let analyzer = RuleBasedAnalyzer;
        let analysis = analyzer.analyze("restaurants near me").await.unwrap();
        assert!(analysis.keywords.contains(&"location".to_string()));
        assert!(analysis.keywords.contains(&"search".to_string()));
    }

    #[tokio::test]
    async fn rule_based_rating_triggers_filter_criterion() {
        let analyzer = RuleBasedAnalyzer;
        let analysis = analyzer.analyze("places with good rating").await.unwrap();
        assert!(analysis.keywords.contains(&"filter".to_string()));
        assert!(
            analysis
                .entities
                .iter()
                .any(|e| e.entity_type == "filter_criterion" && e.value == "reviews")
        );
    }

    #[test]
    fn entity_serde_roundtrip() {
        let entity = Entity {
            entity_type: "amenity".to_string(),
            value: "wifi".to_string(),
        };
        let json = serde_json::to_string(&entity).unwrap();
        let parsed: Entity = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.entity_type, "amenity");
        assert_eq!(parsed.value, "wifi");
    }

    #[test]
    fn subtask_spec_multi_deps() {
        let spec = SubTaskSpec {
            task_type: "merge".to_string(),
            description: "Merge parallel results".to_string(),
            required_capabilities: vec![],
            depends_on: vec![0, 1, 2],
        };
        let json = serde_json::to_string(&spec).unwrap();
        let parsed: SubTaskSpec = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.depends_on, vec![0, 1, 2]);
    }
}
