[package]
name = "arkavo-crypto"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ed25519-dalek = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
base64 = { workspace = true }
thiserror = { workspace = true }
bs58 = "0.5"
p256 = { version = "0.13", features = ["ecdh", "pem"] }

[dev-dependencies]
hex = { workspace = true }
proptest = { workspace = true }
