[package]
name = "arkavo-mcp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "MCP (Model Context Protocol) trait definitions and types for Arkavo"
repository.workspace = true
readme = "README.md"
keywords = ["cli", "ai", "agent", "mcp"]
categories = ["command-line-utilities", "development-tools"]


[dependencies]
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
sha2 = { workspace = true }
toml = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
arkavo-test-macros = { path = "../arkavo-test-macros" }

[lints]
workspace = true
