name: Release

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.tag }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          
      - name: Extract version
        id: version
        run: |
          VERSION=$(grep '^version =' Cargo.toml | head -n 1 | cut -d'"' -f2)
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## Arkavo Edge ${{ steps.version.outputs.tag }}
            
            Release of the Arkavo agentic CLI tool.
            
            ### Installation
            
            Download the appropriate binary for your platform and place it in your PATH.
            
            ### Binaries
            
            - Linux (x64): arkavo-${{ steps.version.outputs.version }}-x86_64-unknown-linux-gnu
            - Linux (ARM64): arkavo-${{ steps.version.outputs.version }}-aarch64-unknown-linux-gnu
            - macOS (ARM64): arkavo-${{ steps.version.outputs.version }}-aarch64-apple-darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
  build-linux-x86_64:
    needs: release
    name: Build Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          profile: minimal
          override: true
          
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu
          
      - name: Prepare binary
        run: |
          cd target/x86_64-unknown-linux-gnu/release
          strip arkavo
          tar -czf arkavo-${{ needs.release.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz arkavo
          shasum -a 256 arkavo-${{ needs.release.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz > arkavo-${{ needs.release.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz.sha256
      
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release.outputs.version }}
          files: |
            ./target/x86_64-unknown-linux-gnu/release/arkavo-${{ needs.release.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz
            ./target/x86_64-unknown-linux-gnu/release/arkavo-${{ needs.release.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-linux-aarch64:
    needs: release
    name: Build Linux (ARM64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          profile: minimal
          override: true
          
      - name: Install cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-unknown-linux-gnu
          use-cross: true
          
      - name: Prepare binary
        run: |
          cd target/aarch64-unknown-linux-gnu/release
          aarch64-linux-gnu-strip arkavo
          tar -czf arkavo-${{ needs.release.outputs.version }}-aarch64-unknown-linux-gnu.tar.gz arkavo
          shasum -a 256 arkavo-${{ needs.release.outputs.version }}-aarch64-unknown-linux-gnu.tar.gz > arkavo-${{ needs.release.outputs.version }}-aarch64-unknown-linux-gnu.tar.gz.sha256
      
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release.outputs.version }}
          files: |
            ./target/aarch64-unknown-linux-gnu/release/arkavo-${{ needs.release.outputs.version }}-aarch64-unknown-linux-gnu.tar.gz
            ./target/aarch64-unknown-linux-gnu/release/arkavo-${{ needs.release.outputs.version }}-aarch64-unknown-linux-gnu.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-macos-arm64:
    needs: release
    name: Build macOS (ARM64)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          profile: minimal
          override: true

      - name: Decode and import signing certificate
        run: |
          echo "${{ secrets.MACOS_CERTIFICATE }}" | base64 --decode > /tmp/certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import /tmp/certificate.p12 -k build.keychain -P "${{ secrets.MACOS_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-apple-darwin

      - name: Strip binary
        run: |
          strip target/aarch64-apple-darwin/release/arkavo

      - name: Codesign binary
        run: |
          codesign --force --options=runtime --timestamp --sign "Developer ID Application: Arkavo LLC (M8GS7ZT95Y)" target/aarch64-apple-darwin/release/arkavo

      - name: Create ZIP for notarization
        run: |
          cd target/aarch64-apple-darwin/release
          zip arkavo.zip arkavo

      - name: Notarize binary
        run: |
          cd target/aarch64-apple-darwin/release
          xcrun notarytool submit arkavo.zip \
            --apple-id ${{ secrets.APPLE_ID }} \
            --password ${{ secrets.APPLE_APP_PASSWORD }} \
            --team-id M8GS7ZT95Y \
            --wait

      - name: Staple notarization
        run: |
          cd target/aarch64-apple-darwin/release
          xcrun stapler staple arkavo

      - name: Prepare binary
        run: |
          cd target/aarch64-apple-darwin/release
          tar -czf arkavo-${{ needs.release.outputs.version }}-aarch64-apple-darwin.tar.gz arkavo
          shasum -a 256 arkavo-${{ needs.release.outputs.version }}-aarch64-apple-darwin.tar.gz > arkavo-${{ needs.release.outputs.version }}-aarch64-apple-darwin.tar.gz.sha256

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release.outputs.version }}
          files: |
            ./target/aarch64-apple-darwin/release/arkavo-${{ needs.release.outputs.version }}-aarch64-apple-darwin.tar.gz
            ./target/aarch64-apple-darwin/release/arkavo-${{ needs.release.outputs.version }}-aarch64-apple-darwin.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
