name: Release

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          
      - name: Extract version
        id: version
        run: |
          VERSION=$(grep '^version =' Cargo.toml | head -n 1 | cut -d'"' -f2)
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          release_name: Release ${{ steps.version.outputs.tag }}
          draft: false
          prerelease: false
          body: |
            ## Arkavo Edge ${{ steps.version.outputs.tag }}
            
            Release of the Arkavo agentic CLI tool.
            
            ### Installation
            
            Download the appropriate binary for your platform and place it in your PATH.
            
            ### Binaries
            
            - Linux (x64): arkavo-${{ steps.version.outputs.version }}-x86_64-unknown-linux-gnu
            - Linux (ARM64): arkavo-${{ steps.version.outputs.version }}-aarch64-unknown-linux-gnu
            - macOS (ARM64): arkavo-${{ steps.version.outputs.version }}-aarch64-apple-darwin
            
  build-linux-x86_64:
    needs: release
    name: Build Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          profile: minimal
          override: true
          
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu
          
      - name: Prepare binary
        run: |
          cd target/x86_64-unknown-linux-gnu/release
          strip arkavo
          tar -czf arkavo-${{ needs.release.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz arkavo
          shasum -a 256 arkavo-${{ needs.release.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz > arkavo-${{ needs.release.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz.sha256
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./target/x86_64-unknown-linux-gnu/release/arkavo-${{ needs.release.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz
          asset_name: arkavo-${{ needs.release.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz
          asset_content_type: application/gzip
          
      - name: Upload Checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./target/x86_64-unknown-linux-gnu/release/arkavo-${{ needs.release.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz.sha256
          asset_name: arkavo-${{ needs.release.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz.sha256
          asset_content_type: text/plain
  
  build-linux-aarch64:
    needs: release
    name: Build Linux (ARM64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          profile: minimal
          override: true
          
      - name: Install cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-unknown-linux-gnu
          use-cross: true
          
      - name: Prepare binary
        run: |
          cd target/aarch64-unknown-linux-gnu/release
          aarch64-linux-gnu-strip arkavo
          tar -czf arkavo-${{ needs.release.outputs.version }}-aarch64-unknown-linux-gnu.tar.gz arkavo
          shasum -a 256 arkavo-${{ needs.release.outputs.version }}-aarch64-unknown-linux-gnu.tar.gz > arkavo-${{ needs.release.outputs.version }}-aarch64-unknown-linux-gnu.tar.gz.sha256
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./target/aarch64-unknown-linux-gnu/release/arkavo-${{ needs.release.outputs.version }}-aarch64-unknown-linux-gnu.tar.gz
          asset_name: arkavo-${{ needs.release.outputs.version }}-aarch64-unknown-linux-gnu.tar.gz
          asset_content_type: application/gzip
          
      - name: Upload Checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./target/aarch64-unknown-linux-gnu/release/arkavo-${{ needs.release.outputs.version }}-aarch64-unknown-linux-gnu.tar.gz.sha256
          asset_name: arkavo-${{ needs.release.outputs.version }}-aarch64-unknown-linux-gnu.tar.gz.sha256
          asset_content_type: text/plain
  
  build-macos-arm64:
    needs: release
    name: Build macOS (ARM64)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          profile: minimal
          override: true
          
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-apple-darwin
          
      - name: Prepare binary
        run: |
          cd target/aarch64-apple-darwin/release
          strip arkavo
          tar -czf arkavo-${{ needs.release.outputs.version }}-aarch64-apple-darwin.tar.gz arkavo
          shasum -a 256 arkavo-${{ needs.release.outputs.version }}-aarch64-apple-darwin.tar.gz > arkavo-${{ needs.release.outputs.version }}-aarch64-apple-darwin.tar.gz.sha256
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./target/aarch64-apple-darwin/release/arkavo-${{ needs.release.outputs.version }}-aarch64-apple-darwin.tar.gz
          asset_name: arkavo-${{ needs.release.outputs.version }}-aarch64-apple-darwin.tar.gz
          asset_content_type: application/gzip
          
      - name: Upload Checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./target/aarch64-apple-darwin/release/arkavo-${{ needs.release.outputs.version }}-aarch64-apple-darwin.tar.gz.sha256
          asset_name: arkavo-${{ needs.release.outputs.version }}-aarch64-apple-darwin.tar.gz.sha256
          asset_content_type: text/plain