[package]
name = "arkavo-llm"
version = "0.2.0"
edition = "2021"
description = "LLM integration for Arkavo Edge"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.75"
thiserror = "1.0.49"
tracing = "0.1.37"

# No features section needed - embedded model is now the only implementation