[package]
name = "arkavo-llm"
version = "0.1.0"
edition = "2021"
description = "LLM integration for Arkavo Edge"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.75"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.49"
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
reqwest = { version = "0.11.22", features = ["json", "stream"] }
futures = "0.3.28"
regex = "1.10.2"